### PR TITLE
Add ManDrill mail api receive email, handle at /api/emails/receive

### PR DESCRIPTION
**Pull request by ndkimhao**
Beta api for receiving email at mandrillapp, no need for delicated server with port 25 opened !

### CODE REVIEW

**Comment by tonerdo** [comment]
Hi ndkimhao,
Thanks for the pull request, could you please explain what this pull request does?
Cheers

**Comment by tonerdo** [comment]
HI @ndkimhao,
I've looked through your code and I kinda guessed what you're trying to achieve, you're using mandrill instead of the built in SMTP server to handle incoming emails, but I just have a few questions;
- How does mandrill know to receive incoming emails on behalf of the domain?
- Are the MX dns records of said domain configured to use Mandrill?

I feel this is a pretty nifty addition and I have no issue merging it, all I need to know now is, have you tested it?

**Comment by ndkimhao** [comment]
I've tested it at https://hmail.ml/ :) I just run it on free openshift account. It works like a charm :))
I think that mandrill is doing better at receiving emails. The first time i tried your page, it cannot recevie mail.

**How does mandrill know to receive incoming emails on behalf of the domain?
You config domain's mx record to mandrill's ip, when they receive email, they will make a POST request to handle address.

**Are the MX dns records of said domain configured to use Mandrill?
Of course :))

##Instruction for setup mandrillapp.com:
Step1 : register account, add inbound domain and config dns mx record
image
image

Step 2 : config route api handle to /api/emails/receive
example, me doamin is hmail.ml, so handle address is http://hmail.ml/api/emails/receive

Step 3 : press "send test" to test api :)
this is example email from mandrill:
image

this is email from guerrillamail
image

**Comment by ndkimhao** [comment]
I have tested your site again, it still can't receive email from sites like guerrillamail, I think there is a problem in SMTP server code

**Comment by tonerdo** [comment]
Okay great @ndkimhao. I want to go ahead and merge it but before I do I'd like to ask that you please include a README.md file on how to set it up with Mandrill, I'll be writing my own readme on how to set it up on a VPS.

Also quick question: I tested out the site at hmail.ml and I must commend that you've made some pretty useful improvements to the user experience, like the reply and inbox refresh, is that included in this pull request as I will like to incorporate it with my own version of the repo.

The homepage of disguise has a fresh new look and you can check it out now here (http://disgui.se) and possibly integrate it into your own fork

**Comment by ndkimhao** [comment]
Yes, i'll do the README.md :)). These new feature I've just added later, I think it must be tested more. There are some new feature: wrap plain text mail with "&lt;pre>" tag, reply, inbox refresh, email copy button and multiple domain support. If you are pleased, I will merge these features to next commit.

Again, sorry if I made English grammar mistake!

**Comment by tonerdo** [comment]
I have no issues with your grammar, it's perfectly understandable. I'd like to include the "<pre>" tag, reply and inbox refresh into my version. I'll go ahead and merge this PR now. So once you're done with the README for the Mandrill part just send another PR.

**Pull request merged**
